#!/bin/sh

bash -ic '
cd .tmp &&
git init &&
echo needle > haystack &&
git add haystack &&
git commit haystack -m "testing Let there be light" &&
git checkout -b foo &&
git checkout -b bar'

./.achieved 'Apprentice Blacksmith (Level 1)'
