#!/bin/sh

bash -ic  '
cd .tmp &&
git init &&
echo needle > haystack &&
git add haystack &&
git commit haystack -m "testing Let there be light" &&
mv .git/hooks/pre-commit{.sample,} &&
git status | cat'

./.achieved 'Carpenter'
