#!/bin/bash -i
. .setup

cd $tmp
git init
echo needle > haystack
git add haystack
git commit haystack -m 'testing Let there be light'
echo foo > bar
git clean -f
cd -

. .teardown
./.achieved 'Cleaning lady'
