#!/bin/sh

bash -ic  '
cd .tmp &&
git init &&
echo needle > haystack &&
git add haystack &&
git commit haystack -m "testing Let there be light" &&
for i in $(seq 1 32); do git log | cat > /dev/null; done'

./.achieved 'Historian (Level 5)'
