#!/bin/sh

bash -ic '
cd .tmp &&
git init &&
echo needle > haystack &&
git add haystack &&
git commit haystack -m "testing Let there be light" &&
git commit --amend -m "testing Seamstress"'

./.achieved 'Seamstress'
