#!/bin/sh

bash -ic '
cd .tmp &&
git init &&
echo needle > haystack &&
git add haystack &&
git commit haystack -m "testing Let there be light" &&
for i in $(seq 1 2);
  do git commit --amend -m "testing Seamstress";
done'

./.achieved 'Seamstress (Level 1)'
